Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,11 +1,24 @@
 name: Demo Of Variables And Context
 
-on: workflow_dispatch
+on:
+  workflow_dispatch:
+    inputs:
+      should_fail:
+        description: 'Shall the step fail? (yes/no)'
+        required: true
+        type: string
+        default: 'no'
 
 jobs:
   build-project:
     runs-on: ubuntu-latest
     steps:
+    - name: Step that can fail
+      run: |
+        echo "Fail check..."
+        if ["${{inputs.should_fail}}" = "yes"]; then
+          exit 1
+        fi
     - uses: actions/checkout@v4
     - name: Build-solution
       run: dotnet build
