Update number.yml

diff --git a/.github/workflows/number.yml b/.github/workflows/number.yml
--- a/.github/workflows/number.yml
+++ b/.github/workflows/number.yml
@@ -3,11 +3,16 @@ name: Ta emot viktig input!
 on:
   workflow_dispatch:
     inputs: 
-      numberInput:
+      number_thing:
         description: "Input very important number plz"
         required: true
-        type: int
+        type: string
         default: '1'
+      should_fail:
+        description: 'Shall the step fail? (yes/no)'
+        required: true
+        type: string
+        default: 'no'
 
 jobs:
   check-input:
@@ -16,9 +21,25 @@ jobs:
     - name: Check if correct number
       run: |
         echo "Failcheck..."
-        if [ "{{inputs.numberInput}}" < 7 ]; then
+        numberInput=${{ github.event.inputs.number_thing }}
+        if (( numberInput < 7 )); then
+          exit 1
+        fi    
+  build-project:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Step that can fail
+      run: |
+        echo "Failcheck..."
+        if [ "${{inputs.should_fail}}" = "yes" ]; then
           exit 1
         fi
+        
+    - uses: actions/checkout@v4
+    - name: Build solution
+      run: dotnet build
+
+
   continue:
     runs-on: ubuntu-latest
     steps:
